name: CI

on:
  push:
    branches: [ master ]
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'cmake/**'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  build-and-test:
    name: ${{ matrix.compiler }}-${{ matrix.build_type }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [gcc, clang]
        build_type: [Sanitize, Release]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Install build tools
        run: sudo apt update && sudo apt install -y clang lld gcc g++ ccache

      - name: Cache ccache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ matrix.compiler }}-${{ matrix.build_type }}

      - name: Configure with CMake Preset
        env:
          CCACHE_DIR: ~/.ccache
          CMAKE_C_COMPILER_LAUNCHER: ccache
          CMAKE_CXX_COMPILER_LAUNCHER: ccache
        run: cmake --preset ${{ matrix.compiler }}-${{ matrix.build_type }}

      - name: Build (Ninja)
        run: cmake --build --preset ${{ matrix.compiler }}-${{ matrix.build_type }}

      - name: Run tests (ctest)
        run: ctest --preset ${{ matrix.compiler }}-${{ matrix.build_type }}
