name: clang-tidy

on:
  push:
    branches: [master]
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
      - '.clang-tidy'
      - 'CMakePresets.json'
      - 'CMakeLists.txt'
      - '.github/workflows/clang-tidy.yml'

jobs:
  lint:
    name: Clang-Tidy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y clang-tidy g++ gcc ninja-build

      - name: Configure project
        run: cmake --preset gcc-RelWithDebInfo

      - name: Run clang-tidy
        run: cmake --build --preset gcc-RelWithDebInfo --target clang-tidy
