name: clang-format

on:
  push:
    branches: [master]
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
      - '.clang-format'
      - '.github/workflows/clang-format.yml'

jobs:
  format-check:
    name: Clang-Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y clang-format gcc g++ ninja-build

      - name: Configure project
        run: cmake --preset gcc-RelWithDebInfo

      - name: Run clang-format
        run: cmake --build --preset gcc-RelWithDebInfo --target format-check
